[package]
name = "qqbot-plugins"
description = "业务插件"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait = { workspace = true }
jieba-rs = { workspace = true }
qqbot-core = { workspace = true }
qqbot-render = { workspace = true }
qqbot-store = { workspace = true }
rand = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync", "time", "macros"] }
tracing = { workspace = true }

[lints]
workspace = true
